jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID:-admin}
         password: ${JENKINS_ADMIN_PASSWORD:-password}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
  numExecutors: 2
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080/
jobs:
    - script: >
        job('GitHub_SCM') {
            scm {
                git('https://github.com/Levi-Michael/auto-deploy-jenkins.git')
            }
            triggers {
                scm('* * * * *')
            }
            steps {
                shell('python3 main.py')
            }
        }
